name: Check Specs with RSpec
on:
  push:
    paths: [.github/workflows/spec.yml, lib/**, spec/**]
  pull_request:
    paths: [.github/workflows/spec.yml, lib/**, spec/**]
jobs:
  
  spec:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3', '3.0', '2', '2.0']
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
      env:
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: Bearer:${{ github.token }}
    
    - name: Check Specs with RSpec
      run: bundle exec rspec
